/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageScalePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  maintainAspectRatio: true,
  showDimensionsWhileResizing: true,
  minWidth: 50,
  minHeight: 50,
  handleSize: 10,
  handleColor: "#4A9EFF"
};
var ImageScaleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Maintain aspect ratio").setDesc("Keep the image proportions when resizing").addToggle((toggle) => toggle.setValue(this.plugin.settings.maintainAspectRatio).onChange(async (value) => {
      this.plugin.settings.maintainAspectRatio = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show dimensions while resizing").setDesc("Display image dimensions during resize operation").addToggle((toggle) => toggle.setValue(this.plugin.settings.showDimensionsWhileResizing).onChange(async (value) => {
      this.plugin.settings.showDimensionsWhileResizing = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Minimum width").setDesc("Minimum width for resized images (in pixels)").addText((text) => text.setPlaceholder("50").setValue(this.plugin.settings.minWidth.toString()).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.minWidth = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Minimum height").setDesc("Minimum height for resized images (in pixels)").addText((text) => text.setPlaceholder("50").setValue(this.plugin.settings.minHeight.toString()).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.minHeight = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Handle size").setDesc("Size of the resize handles (in pixels)").addText((text) => text.setPlaceholder("10").setValue(this.plugin.settings.handleSize.toString()).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.handleSize = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Handle color").setDesc("Color of the resize handles (hex color)").addText((text) => text.setPlaceholder("#4A9EFF").setValue(this.plugin.settings.handleColor).onChange(async (value) => {
      if (/^#[0-9A-F]{6}$/i.test(value)) {
        this.plugin.settings.handleColor = value;
        await this.plugin.saveSettings();
      }
    }));
  }
};

// imageResizer.ts
var import_obsidian2 = require("obsidian");
var ImageResizer = class {
  constructor(app, plugin, settings) {
    this.activeImage = null;
    this.handles = [];
    this.overlay = null;
    this.dimensionDisplay = null;
    this.isResizing = false;
    this.startX = 0;
    this.startY = 0;
    this.startWidth = 0;
    this.startHeight = 0;
    this.aspectRatio = 1;
    this.currentHandle = null;
    this.processedImages = /* @__PURE__ */ new WeakSet();
    this.finalWidth = 0;
    this.finalHeight = 0;
    this.app = app;
    this.plugin = plugin;
    this.settings = settings;
    this.addStyles();
  }
  cleanup() {
    this.deactivateResize();
  }
  addStyles() {
    const isTouchDevice = "ontouchstart" in window || navigator.maxTouchPoints > 0;
    const handleSize = isTouchDevice ? Math.max(this.settings.handleSize, 15) : this.settings.handleSize;
    activeDocument.body.setCssProps({
      "--handle-color": this.settings.handleColor,
      "--handle-size": `${handleSize}px`
    });
  }
  toggleImageResize(img) {
    if (this.activeImage === img) {
      this.deactivateResize();
    } else {
      this.activateResize(img, null);
    }
  }
  makeImageResizable(img, context) {
    var _a, _b, _c, _d;
    if (this.processedImages.has(img)) {
      return;
    }
    this.processedImages.add(img);
    img.dataset.imageScaleProcessed = "true";
    const src = img.getAttribute("src") || (img instanceof HTMLImageElement ? img.src : "") || "";
    if (src) {
      const filename = (_b = (_a = src.split("/").pop()) == null ? void 0 : _a.split("?")[0]) == null ? void 0 : _b.split("#")[0];
      if (filename) {
        img.dataset.imageFilename = filename;
      }
    }
    const isPdfDiv = !!((_c = img.classList) == null ? void 0 : _c.contains("pdf-embed")) || !!((_d = img.classList) == null ? void 0 : _d.contains("internal-embed"));
    const isImage = img.tagName === "IMG";
    if (isPdfDiv) {
      const file = this.app.workspace.getActiveFile();
      if (file) {
        this.app.vault.read(file).then((content) => {
          var _a2;
          const lines = content.split("\n");
          const pdfSrc = img.getAttribute("src") || "";
          const cleanSrc = pdfSrc.split("#")[0];
          const srcFilename = (_a2 = cleanSrc.split("/").pop()) == null ? void 0 : _a2.split("?")[0];
          for (const line of lines) {
            if (line.includes(srcFilename || "") && line.includes("<!-- pdf-scale:")) {
              const scaleMatch = line.match(/<!-- pdf-scale:([\d.]+) -->/);
              if (scaleMatch) {
                const scale = parseFloat(scaleMatch[1]);
                this.applyPdfScale(img, scale);
              }
              break;
            }
          }
        }).catch((err) => {
          console.error("Error reading file for PDF scale:", err);
        });
      }
    }
    if (isImage && !img.complete) {
      img.addEventListener("load", () => {
        this.processedImages.delete(img);
        delete img.dataset.imageScaleProcessed;
        this.makeImageResizable(img, context);
      }, { once: true });
      return;
    }
    if (isImage && (!img.naturalWidth || !img.naturalHeight)) {
      return;
    }
    img.classList.add("image-scale-clickable");
    img.title = "Click to resize";
  }
  applyPdfScale(pdfDiv, scale) {
    pdfDiv.classList.add("image-scale-pdf-scaled");
    pdfDiv.setCssProps({ "--pdf-scale": String(scale) });
  }
  activateResize(img, context) {
    var _a, _b;
    if (this.activeImage && this.activeImage !== img) {
      this.deactivateResize();
    }
    this.activeImage = img;
    img.classList.add("image-scale-active");
    const isIframeOrPdf = img.tagName === "IFRAME" || !!((_a = img.classList) == null ? void 0 : _a.contains("pdf-embed"));
    if (isIframeOrPdf) {
      this.aspectRatio = img.clientWidth / img.clientHeight || 16 / 9;
    } else {
      const image = img;
      this.aspectRatio = image.naturalWidth / image.naturalHeight;
    }
    const doc = activeDocument;
    const win = activeWindow;
    this.overlay = doc.createElement("div");
    this.overlay.classList.add("image-scale-overlay");
    doc.body.appendChild(this.overlay);
    this.positionOverlay(img);
    const positions = ["nw", "ne", "sw", "se"];
    positions.forEach((pos) => {
      var _a2;
      const handle = doc.createElement("div");
      handle.classList.add("image-scale-handle", pos);
      handle.addEventListener("mousedown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.startResize(e, pos, img, context);
      });
      handle.addEventListener("touchstart", (e) => {
        e.preventDefault();
        e.stopPropagation();
        const touch = e.touches[0];
        const mouseEvent = new MouseEvent("mousedown", {
          clientX: touch.clientX,
          clientY: touch.clientY,
          bubbles: true,
          cancelable: true
        });
        this.startResize(mouseEvent, pos, img, context);
      }, { passive: false });
      handle.addEventListener("touchmove", (e) => {
        e.preventDefault();
      }, { passive: false });
      (_a2 = this.overlay) == null ? void 0 : _a2.appendChild(handle);
      this.handles.push({ element: handle, position: pos });
    });
    if (this.settings.showDimensionsWhileResizing) {
      this.dimensionDisplay = doc.createElement("div");
      this.dimensionDisplay.classList.add("image-scale-dimension-display");
      const width = (img instanceof HTMLImageElement ? img.width : 0) || img.clientWidth;
      const height = (img instanceof HTMLImageElement ? img.height : 0) || img.clientHeight;
      this.updateDimensionDisplay(width, height);
      (_b = this.overlay) == null ? void 0 : _b.appendChild(this.dimensionDisplay);
    }
    const deactivateHandler = (e) => {
      var _a2;
      const target = e.target;
      if (!img.contains(target) && !((_a2 = this.overlay) == null ? void 0 : _a2.contains(target))) {
        this.deactivateResize();
        doc.removeEventListener("click", deactivateHandler);
      }
    };
    win.setTimeout(() => {
      doc.addEventListener("click", deactivateHandler);
    }, 0);
  }
  positionOverlay(img) {
    var _a, _b;
    if (!this.overlay)
      return;
    const rect = img.getBoundingClientRect();
    const isPdfDiv = !!((_a = img.classList) == null ? void 0 : _a.contains("pdf-embed")) || !!((_b = img.classList) == null ? void 0 : _b.contains("internal-embed"));
    this.overlay.setCssStyles({
      top: rect.top + "px",
      left: rect.left + "px"
    });
    if (!isPdfDiv || !this.isResizing) {
      this.overlay.setCssStyles({
        width: rect.width + "px",
        height: rect.height + "px"
      });
    }
  }
  deactivateResize() {
    if (this.activeImage) {
      this.activeImage.classList.remove("image-scale-active");
      this.activeImage = null;
    }
    if (this.overlay) {
      this.overlay.remove();
      this.overlay = null;
    }
    if (this.dimensionDisplay) {
      this.dimensionDisplay.remove();
      this.dimensionDisplay = null;
    }
    this.handles = [];
  }
  startResize(e, handle, img, context) {
    e.preventDefault();
    this.isResizing = true;
    this.currentHandle = handle;
    this.startX = e.clientX;
    this.startY = e.clientY;
    if (img instanceof HTMLImageElement) {
      this.startWidth = img.width;
      this.startHeight = img.height;
    } else {
      this.startWidth = img.clientWidth;
      this.startHeight = img.clientHeight;
    }
    const doc = activeDocument;
    const win = activeWindow;
    const mouseMoveHandler = (ev) => this.onResize(ev, img);
    const touchMoveHandler = (ev) => {
      ev.preventDefault();
      const touch = ev.touches[0];
      const mouseEvent = new MouseEvent("mousemove", {
        clientX: touch.clientX,
        clientY: touch.clientY,
        bubbles: true,
        cancelable: true
      });
      this.onResize(mouseEvent, img);
    };
    const mouseUpHandler = (_ev) => {
      void (async () => {
        var _a;
        this.isResizing = false;
        doc.removeEventListener("mousemove", mouseMoveHandler);
        doc.removeEventListener("mouseup", mouseUpHandler);
        doc.removeEventListener("touchmove", touchMoveHandler);
        doc.removeEventListener("touchend", mouseUpHandler);
        doc.removeEventListener("touchcancel", mouseUpHandler);
        new import_obsidian2.Notice("Saving resize...");
        await new Promise((resolve) => win.setTimeout(resolve, 100));
        try {
          if (img instanceof HTMLImageElement) {
            await this.updateMarkdown(img, context);
          } else if ((_a = img.classList) == null ? void 0 : _a.contains("pdf-embed")) {
            await this.updatePdfMarkdown(img, context);
          }
        } catch (error) {
          new import_obsidian2.Notice("Error saving resize: " + error.message);
        }
      })();
    };
    doc.addEventListener("mousemove", mouseMoveHandler);
    doc.addEventListener("mouseup", mouseUpHandler);
    doc.addEventListener("touchmove", touchMoveHandler, { passive: false });
    doc.addEventListener("touchend", mouseUpHandler);
    doc.addEventListener("touchcancel", mouseUpHandler);
  }
  onResize(e, img) {
    var _a, _b;
    if (!this.isResizing || !this.currentHandle)
      return;
    const deltaX = e.clientX - this.startX;
    const deltaY = e.clientY - this.startY;
    let newWidth = this.startWidth;
    let newHeight = this.startHeight;
    switch (this.currentHandle) {
      case "se":
        newWidth = this.startWidth + deltaX;
        newHeight = this.startHeight + deltaY;
        break;
      case "sw":
        newWidth = this.startWidth - deltaX;
        newHeight = this.startHeight + deltaY;
        break;
      case "ne":
        newWidth = this.startWidth + deltaX;
        newHeight = this.startHeight - deltaY;
        break;
      case "nw":
        newWidth = this.startWidth - deltaX;
        newHeight = this.startHeight - deltaY;
        break;
    }
    if (this.settings.maintainAspectRatio) {
      const widthChange = Math.abs(newWidth - this.startWidth);
      const heightChange = Math.abs(newHeight - this.startHeight);
      if (widthChange > heightChange) {
        newHeight = newWidth / this.aspectRatio;
      } else {
        newWidth = newHeight * this.aspectRatio;
      }
    }
    newWidth = Math.max(newWidth, this.settings.minWidth);
    newHeight = Math.max(newHeight, this.settings.minHeight);
    this.finalWidth = Math.round(newWidth);
    this.finalHeight = Math.round(newHeight);
    const isPdfDiv = !!((_a = img.classList) == null ? void 0 : _a.contains("pdf-embed")) || !!((_b = img.classList) == null ? void 0 : _b.contains("internal-embed"));
    if (!isPdfDiv) {
      img.setCssStyles({
        width: `${newWidth}px`,
        height: `${newHeight}px`
      });
      if (img instanceof HTMLImageElement) {
        img.width = Math.round(newWidth);
        img.height = Math.round(newHeight);
      }
    }
    if (this.overlay && isPdfDiv) {
      this.overlay.setCssStyles({
        width: `${newWidth}px`,
        height: `${newHeight}px`
      });
    }
    this.positionOverlay(img);
    if (this.dimensionDisplay) {
      this.updateDimensionDisplay(Math.round(newWidth), Math.round(newHeight));
    }
  }
  updateDimensionDisplay(width, height) {
    if (this.dimensionDisplay) {
      this.dimensionDisplay.textContent = `${width} \xD7 ${height}`;
    }
  }
  async updateMarkdown(img, context) {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian2.Notice("No active file found");
      return;
    }
    const width = this.finalWidth || Math.round(img.width);
    const height = this.finalHeight || Math.round(img.height);
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      new import_obsidian2.Notice("No active markdown view");
      return;
    }
    const editor = view.editor;
    const content = editor.getValue();
    const lines = content.split("\n");
    let updated = false;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      let newLine = line;
      newLine = newLine.replace(/!\[\[([^\]]+?)(?:\|\d+(?:x\d+)?)?\]\]/g, (_match, path) => {
        updated = true;
        return `![[${path}|${width}]]`;
      });
      if (newLine === line) {
        newLine = newLine.replace(/!\[([^\]]*)\]\(([^)]+?)(?:\|\d+(?:x\d+)?)?\)/g, (_match, alt, path) => {
          updated = true;
          const newSize = this.settings.maintainAspectRatio ? width : `${width}x${height}`;
          return `![${alt}](${path}|${newSize})`;
        });
      }
      if (newLine !== line) {
        lines[i] = newLine;
      }
    }
    if (updated) {
      try {
        const newContent = lines.join("\n");
        editor.setValue(newContent);
        new import_obsidian2.Notice(`Image resized to ${width}\xD7${height}px`);
      } catch (error) {
        new import_obsidian2.Notice("Error saving: " + error.message);
      }
    } else {
      new import_obsidian2.Notice("No image syntax found in file");
    }
  }
  async updatePdfMarkdown(pdfDiv, context) {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian2.Notice("No active file found");
      return;
    }
    let width;
    let height;
    if (this.overlay) {
      width = Math.round(parseFloat(this.overlay.style.width) || pdfDiv.clientWidth);
      height = Math.round(parseFloat(this.overlay.style.height) || pdfDiv.clientHeight);
    } else {
      width = Math.round(pdfDiv.clientWidth);
      height = Math.round(pdfDiv.clientHeight);
    }
    const src = pdfDiv.getAttribute("src") || "";
    const cleanSrc = src.split("#")[0];
    const originalWidth = pdfDiv.scrollWidth;
    const originalHeight = pdfDiv.scrollHeight;
    const baseWidth = originalWidth || pdfDiv.clientWidth;
    const baseHeight = originalHeight || pdfDiv.clientHeight;
    const scaleX = width / baseWidth;
    const scaleY = height / baseHeight;
    const scale = Math.min(scaleX, scaleY);
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    let updated = false;
    const newContent = lines.map((line) => {
      if (updated)
        return line;
      if (line.toLowerCase().includes(".pdf")) {
        const wikilinkPattern = /!\[\[([^#|\]]+\.pdf)(?:#[^\]]+)?(?:\|[^\]]+)?\]\](?:<!--\s*pdf-scale:[\d.]+\s*-->)?/gi;
        const newLine = line.replace(wikilinkPattern, (match, pdfPath) => {
          var _a, _b;
          if (cleanSrc) {
            const srcFilename = (_a = cleanSrc.split("/").pop()) == null ? void 0 : _a.split("?")[0];
            const pathFilename = (_b = pdfPath.split("/").pop()) == null ? void 0 : _b.split("?")[0];
            if (srcFilename !== pathFilename && pdfPath !== cleanSrc && decodeURIComponent(pdfPath) !== cleanSrc) {
              return match;
            }
          }
          updated = true;
          return `![[${pdfPath}]]<!-- pdf-scale:${scale.toFixed(3)} -->`;
        });
        if (updated) {
          return newLine;
        }
      }
      return line;
    }).join("\n");
    if (updated) {
      try {
        await this.app.vault.modify(file, newContent);
        this.applyPdfScale(pdfDiv, scale);
        this.deactivateResize();
        new import_obsidian2.Notice(`PDF scaled to ${Math.round(scale * 100)}%`);
      } catch (error) {
        new import_obsidian2.Notice("Error saving PDF resize: " + error.message);
      }
    } else {
      new import_obsidian2.Notice("Could not update markdown - PDF not found in file");
    }
  }
  escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
};

// main.ts
var import_view = require("@codemirror/view");
var pdfScaleCommentPattern = /<!--\s*pdf-scale:[\d.]+\s*-->/g;
function createPdfScaleCommentHider() {
  return import_view.ViewPlugin.fromClass(class {
    constructor(view) {
      this.decorations = this.buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = this.buildDecorations(update.view);
      }
    }
    buildDecorations(view) {
      const decorations = [];
      const activeLines = /* @__PURE__ */ new Set();
      for (const range of view.state.selection.ranges) {
        activeLines.add(view.state.doc.lineAt(range.head).number);
      }
      for (const visibleRange of view.visibleRanges) {
        let position = visibleRange.from;
        while (position <= visibleRange.to) {
          const line = view.state.doc.lineAt(position);
          if (!activeLines.has(line.number)) {
            const text = line.text;
            pdfScaleCommentPattern.lastIndex = 0;
            let match;
            while ((match = pdfScaleCommentPattern.exec(text)) !== null) {
              decorations.push(import_view.Decoration.replace({}).range(line.from + match.index, line.from + match.index + match[0].length));
            }
          }
          if (line.to >= visibleRange.to)
            break;
          position = line.to + 1;
        }
      }
      return import_view.Decoration.set(decorations, true);
    }
  }, {
    decorations: (plugin) => plugin.decorations
  });
}
var ImageScalePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.observer = null;
  }
  async onload() {
    await this.loadSettings();
    this.resizer = new ImageResizer(this.app, this, this.settings);
    this.addSettingTab(new ImageScaleSettingTab(this.app, this));
    this.registerEditorExtension(createPdfScaleCommentHider());
    this.registerMarkdownPostProcessor((element, context) => {
      const images = element.querySelectorAll("img");
      images.forEach((img) => {
        this.resizer.makeImageResizable(img, context);
      });
      const pdfEmbeds = element.querySelectorAll(".pdf-embed, .internal-embed.pdf-embed");
      pdfEmbeds.forEach((pdfDiv) => {
        this.resizer.makeImageResizable(pdfDiv, context);
      });
    });
    this.app.workspace.onLayoutReady(() => {
      this.startObserving();
      this.processAllImages();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.processAllImages();
      })
    );
    this.registerDomEvent(activeDocument, "click", (evt) => {
      const target = evt.target;
      if (target.tagName === "IMG") {
        const img = target;
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (markdownView && markdownView.contentEl.contains(img)) {
          evt.preventDefault();
          evt.stopPropagation();
          this.resizer.toggleImageResize(img);
          return false;
        }
      }
      if (target.classList.contains("textLayerNode") || target.classList.contains("textLayer") || target.classList.contains("pdf-toolbar") || target.classList.contains("pdfViewer") || target.classList.contains("pdf-container") || target.tagName === "CANVAS" || target.closest(".textLayer, .pdf-toolbar, .pdfViewer, .pdf-container")) {
        const pdfEmbed = target.closest(".internal-embed.pdf-embed, .pdf-embed");
        if (pdfEmbed) {
          const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
          if (markdownView && markdownView.contentEl.contains(pdfEmbed)) {
            evt.preventDefault();
            evt.stopPropagation();
            this.resizer.toggleImageResize(pdfEmbed);
            return false;
          }
        }
      }
    }, true);
    this.addCommand({
      id: "reset-image-size",
      name: "Reset size to original",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const imageRegex = /!\[([^\]]*)\]\(([^)]+?)(?:\s*\|(\d+)(?:x(\d+))?)?\)/g;
        let match;
        while ((match = imageRegex.exec(line)) !== null) {
          const start = match.index;
          const end = start + match[0].length;
          if (cursor.ch >= start && cursor.ch <= end) {
            const alt = match[1];
            const url = match[2];
            const newImageMd = `![${alt}](${url})`;
            editor.replaceRange(
              newImageMd,
              { line: cursor.line, ch: start },
              { line: cursor.line, ch: end }
            );
            new import_obsidian3.Notice("Image size reset");
            return;
          }
        }
        new import_obsidian3.Notice("No image found at cursor");
      }
    });
  }
  onunload() {
    if (this.observer) {
      this.observer.disconnect();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  startObserving() {
    this.observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.addedNodes.length > 0) {
          mutation.addedNodes.forEach((node) => {
            if (node.instanceOf(HTMLElement)) {
              const images = node.querySelectorAll("img");
              images.forEach((img) => {
                this.resizer.makeImageResizable(img, null);
              });
              if (node.tagName === "IMG") {
                this.resizer.makeImageResizable(node, null);
              }
              const pdfEmbeds = node.querySelectorAll(".pdf-embed, .internal-embed.pdf-embed");
              pdfEmbeds.forEach((pdfDiv) => {
                this.resizer.makeImageResizable(pdfDiv, null);
              });
              if (node.classList.contains("pdf-embed")) {
                this.resizer.makeImageResizable(node, null);
              }
            }
          });
        }
      }
    });
    this.observer.observe(activeDocument.body, {
      childList: true,
      subtree: true
    });
  }
  processAllImages() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!activeView)
      return;
    const container = activeView.contentEl;
    const images = container.querySelectorAll("img");
    images.forEach((img) => {
      if (!img.dataset.imageScaleProcessed) {
        this.resizer.makeImageResizable(img, null);
      }
    });
    const pdfEmbeds = container.querySelectorAll(".pdf-embed, .internal-embed.pdf-embed");
    pdfEmbeds.forEach((pdfDiv) => {
      if (!pdfDiv.dataset.imageScaleProcessed) {
        this.resizer.makeImageResizable(pdfDiv, null);
      }
    });
  }
};

/* nosourcemap */